- group: {name: future, enabled: true}
- group: {name: generalise, enabled: true}
- group: {name: generalise-for-conciseness, enabled: true}
- group: {name: dollar, enabled: true}
- group: {name: teaching, enabled: true}
