name:                wled-json
version:             0.0.1.1
github:              "alaendle/wled-json"
license:             BSD-3-Clause
author:              "Andreas Ländle"
#maintainer:          "example@example.com"
copyright:           "2024-2025 Andreas Ländle"

extra-source-files:
- README.md

extra-doc-files:
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Convenient interface for interacting with WLED devices
category:            Interfaces

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alaendle/wled-json#readme>

dependencies:
- base >= 4.7 && < 5

tested-with:
- GHC == 9.2.8
- GHC == 9.4.8
- GHC == 9.6.7
- GHC == 9.8.4
- GHC == 9.10.2
- GHC == 9.12.2

ghc-options:
- -O0
- -Weverything
#- -Werror
- -Wno-unsafe
- -Wno-missing-import-lists
- -Wno-prepositive-qualified-module
- -Wno-implicit-prelude
- -Wno-missing-safe-haskell-mode
- -Wno-safe
- -Wno-missing-role-annotations

library:
  source-dirs: src
  dependencies:
  - barbies >= 2.0.5 && < 2.2
  - aeson >= 2.2.3 && < 2.3
  - bytestring >= 0.11.5.3 && < 0.13
  - deriving-aeson >= 0.2.9 && < 0.3
  - http-conduit >= 2.3.9.1 && < 2.4

executables:
  wled-json-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wled-json
    - rhine >= 1.4.0.1 && < 1.6
  wled-json-simple:
    main:                Main.hs
    source-dirs:         app-simple
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wled-json

tests:
  wled-json-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wled-json
    - aeson
    - hspec
    - QuickCheck
    verbatim: |
      build-tool-depends:
          hspec-discover:hspec-discover